import sys
from math import *
from OpenGL.GL import *
from OpenGL.GLU import *
from OpenGL.GLUT import *
import random
#Important windo parameters
width = 800
height = 800
#Global Parameters declared
colorR=1.0
colorB=0.0
colorG=0.0
matrix = []
#Parameters to draw the L-System is declared
FILENAME='lsystems.txt'
AXIOM=None
RULES={}
ANGLE=None
VARIABLES = None
SIZE=None
ITERATE=None
SHAPE=''
TREE=False
TD=0

#Class encapsulation of world coordinates
class Coord:
	def __init__(self,l=0,r=0,b=0,t=0):
		self.l = l
		self.r = r
		self.t = t
		self.b = b

world_coord = Coord(-1,2,-0.5,2)
XS = SIZE
#Function to apply an iteration i.e apply rules to the axiom passed to the function
def Lindenmayer(axiom,rules):
	rules = rules.items()
	
	def apply_rule(axiom,(symbol,replacement)):    
		return axiom.replace(symbol,replacement.lower())

	while True:
		# Create a generator function
		yield axiom
		#get the next iteration of the system
		axiom = reduce(apply_rule,rules,axiom).upper()

#Class to generate the list of iteration when a particular iteration no. is being specified
class GenerateList(object):
	def __init__(self,generator):
		self.__generator = generator
		self.__list = []

	#to store the previous iterations and return the asked iteration string
	def __getitem__(self,index):
		for i in range(index-len(self.__list) +1):
			self.__list.append(self.__generator.next())
		return self.__list[index]


#Main class to apply the the drawing rules specified in the string returned by GenrateList.
class L_System(GenerateList):
    """
	Sample class to manipulate the L String generated by Lindenmayer function defined above.

	It is expected that the user follows the following convention to define the rules, Source
	http://en.wikipedia.org/wiki/L-system

	'F': Draw a Line
	'+': Turn Right by predefined angle i.e. objects angle
	'-': Turn Left by predefined angle
	'G': Move forward without drawing
	']': Restore previously saved states
	'[': Save current state
	'&': Pitch down
	'^': Pitch up
	'\\': Roll left
	'/': Roll right

    """

    def __init__(self,offset,start,rules,angle):
        self.offset = offset
        self.states = []
        self.angle = angle
        self.actions = {
        'F': self.forward,
        '+': self.right,
        '-': self.left,
        'G': self.go,
        '[': self.save,
        ']': self.restore,
        '&': self.pitchDown,
        '^': self.pitchUp,
        '\\': self.rollLeft,
        '/': self.rollRight
        }
        super(L_System, self).__init__(Lindenmayer(start, rules))

#Draw different shapes
    def drawShape(self,which):
        global SIZE,colorR, colorB, colorG
        #glColor3d(random.random(),random.random(),random.random())
        if which == "line" and TREE == True:
            glBegin(GL_LINES)
            glVertex3d(0,0,0)
            glVertex3d(0,self.offset,0)
            glEnd()
        elif which == "quad" :
		glBegin(GL_QUADS);			# Start Drawing The Cube


		glColor3f(0.0,1.0,0.0);			# Set The Color To Blue
		glVertex3f( self.offset, self.offset,-self.offset);		# Top Right Of The Quad (Top)
		glVertex3f(-self.offset, self.offset,-self.offset);		# Top Left Of The Quad (Top)
		glVertex3f(-self.offset, self.offset, self.offset);		# Bottom Left Of The Quad (Top)
		glVertex3f( self.offset, self.offset, self.offset);		# Bottom Right Of The Quad (Top)

		glColor3f(1.0,0.5,0.0);			# Set The Color To Orange
		glVertex3f( self.offset,-self.offset, self.offset);		# Top Right Of The Quad (Bottom)
		glVertex3f(-self.offset,-self.offset, self.offset);		# Top Left Of The Quad (Bottom)
		glVertex3f(-self.offset,-self.offset,-self.offset);		# Bottom Left Of The Quad (Bottom)
		glVertex3f( self.offset,-self.offset,-self.offset);		# Bottom Right Of The Quad (Bottom)

		glColor3f(1.0,0.0,0.0);			# Set The Color To Red
		glVertex3f( self.offset, self.offset, self.offset);		# Top Right Of The Quad (Front)
		glVertex3f(-self.offset, self.offset, self.offset);		# Top Left Of The Quad (Front)
		glVertex3f(-self.offset,-self.offset, self.offset);		# Bottom Left Of The Quad (Front)
		glVertex3f( self.offset,-self.offset, self.offset);		# Bottom Right Of The Quad (Front)

		glColor3f(1.0,1.0,0.0);			# Set The Color To Yellow
		glVertex3f( self.offset,-self.offset,-self.offset);		# Bottom Left Of The Quad (Back)
		glVertex3f(-self.offset,-self.offset,-self.offset);		# Bottom Right Of The Quad (Back)
		glVertex3f(-self.offset, self.offset,-self.offset);		# Top Right Of The Quad (Back)
		glVertex3f( self.offset, self.offset,-self.offset);		# Top Left Of The Quad (Back)

		glColor3f(0.0,0.0,1.0);			# Set The Color To Blue
		glVertex3f(-self.offset, self.offset, self.offset);		# Top Right Of The Quad (Left)
		glVertex3f(-self.offset, self.offset,-self.offset);		# Top Left Of The Quad (Left)
		glVertex3f(-self.offset,-self.offset,-self.offset);		# Bottom Left Of The Quad (Left)
		glVertex3f(-self.offset,-self.offset, self.offset);		# Bottom Right Of The Quad (Left)

		glColor3f(1.0,0.0,1.0);			# Set The Color To Violet
		glVertex3f( self.offset, self.offset,-self.offset);		# Top Right Of The Quad (Right)
		glVertex3f( self.offset, self.offset, self.offset);		# Top Left Of The Quad (Right)
		glVertex3f( self.offset,-self.offset, self.offset);		# Bottom Left Of The Quad (Right)
		glVertex3f( self.offset,-self.offset,-self.offset);		# Bottom Right Of The Quad (Right)
		glEnd();				# Done Drawing The Quad
            #glBegin(GL_POLYGON)
            #glVertex2d(0,0)
            #glVertex2d(self.offset,0)
            #glVertex2d(self.offset,self.offset)
            #glVertex2d(0,self.offset)
            #glEnd()
        elif which=="circle" :
            glBegin(GL_LINE_LOOP)
            for ang in range(0, 360, 5):
                x = cos(ang*pi/180)*SIZE
                y = sin(ang*pi/180)*SIZE
                glVertex2d(x, y)
            glEnd()
        elif which == "line" and TREE == False:
            glBegin(GL_LINES)
            glVertex3d(0,0,0)
            glVertex3d(self.offset,0,0)
            glEnd()
#Move forward
    def forward(self):
		global SHAPE
		self.drawShape(SHAPE)
		if TREE==True:
			glTranslatef(0,self.offset,0)
		else:
			glTranslatef(self.offset,0,0)
#Rotate Right
    def right(self): glRotated(self.angle,0,0,1)

#Rotate Left
    def left(self): glRotated(-self.angle,0,0,1)

#Jump forward without drawing
    def go(self):
		if TREE==True:
			glTranslatef(0,self.offset,0)
		else:
			glTranslatef(self.offset,0,0)
    #Save the state
    def save(self):
		global matrix
		temp = glGetFloatv(GL_MODELVIEW_MATRIX)
		matrix.append(temp)
	#Restore the last saved state
    def restore(self):
		global matrix
		temp = matrix.pop()
		glLoadMatrixd(temp)
	
    def pitchDown(self): glRotated(self.angle, 1,0,0)

    def pitchUp (self): glRotated(-self.angle, 1,0,0)

    def rollLeft (self): glRotated (self.angle, 0,1,0)
	
    def rollRight (self): glRotated (-self.angle, 0,1,0)
	
    def update(self): pass
    
#Draw the LSystem with iter = index
    def draw(self, index):
        global TD,XS
        glColor3d(colorR,colorB,colorG)
        glLineWidth(1)
        glLoadIdentity()
        glPushMatrix()
        glTranslatef(XS,0,0)
        glRotated(TD, 0,1,0)
        print TD
        print SIZE
        print self[index]
        for char in self[index]:
            if char in self.actions:
                self.actions[char]()
	glFlush()
        glPopMatrix()


def display():
    print "inside display"
    initialize()
    glLoadIdentity()
    glClear (GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT)
    gluLookAt(0.0,0.0,8.0,0.0,0.0,0.0,0.0,1.0,0.0)


def file_handle():
    try:
        global AXIOM,RULES,ANGLE,SIZE,ITERATE,SHAPE,XS,TREE
        fin = open(FILENAME,"r")
        lineList = fin.readlines()
        fin.close()
	TREE=True
        for line in lineList:
            temp = line.split(";")
            if temp[0] == "Va":
                VARIABLES = temp[1].rstrip()
            elif temp[0] == "Ax":
                AXIOM = temp[1].rstrip()
            elif temp[0] == "Ru":
                key, val = temp[1].rstrip().split(":")[0],temp[1].rstrip().split(":")[1]
                RULES[key] = val
            elif temp[0] == "An":
                ANGLE = int(temp[1].rstrip()) 
            elif temp[0] == "Si":
                SIZE = float(temp[1].rstrip())
                XS = SIZE
            elif temp[0] == "It":
                ITERATE = int(temp[1].rstrip())
            elif temp[0] == "Sh":
                SHAPE = temp[1].rstrip()
    except IOError:
        print "File Not Found"
        sys_exit(1)
    DrawSystem()
    return 0

def onResize(w,h):
    global width,height,world_coord
    width,height = (w,h)
    glViewport(0,0,w,h)
    cx = 0.5*(world_coord.l + world_coord.r )
    dy = world_coord.t - world_coord.b
    world_coord.l = cx - 0.5*dy * w/h
    world_coord.r = cx + 0.5*dy * w/h
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    #gluOrtho2D(world_coord.l,world_coord.r,world_coord.b,world_coord.t)
    gluPerspective(40.0,w/h,5,20.0)
    glMatrixMode(GL_MODELVIEW)

def DrawSystem():
    global SIZE, AXIOM,RULES,ANGLE,ITERATE
    glClearDepth(1.0)
    glClear (GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT)
    L_System( SIZE,AXIOM, RULES,ANGLE).draw(ITERATE)
    return 0


def createMenu():
	submenu1 = glutCreateMenu(processMenuEvents)
	glutAddMenuEntry("Dragon",1)
	glutAddMenuEntry("Snowflake",2)
	glutAddMenuEntry("Sierpinsky",3)
	glutAddMenuEntry("Plant",4)
	submenu2 = glutCreateMenu(colorChange)
	glutAddMenuEntry("Red",4)
	glutAddMenuEntry("Orange",5)
	submenu3 = glutCreateMenu(shapeChange)
	glutAddMenuEntry("Line",1)
	glutAddMenuEntry("Circle",2)
	glutAddMenuEntry("Square",3)
	glutCreateMenu(processMenuEvents)
	glutAddSubMenu("color",submenu2)
	glutAddSubMenu("System",submenu1)
	glutAddSubMenu("Shapes",submenu3)
	glutAddMenuEntry("Load File",5)
	glutAttachMenu (GLUT_MIDDLE_BUTTON)

def shapeChange(option):
	global SHAPE
	if option  == 1:
		SHAPE = "line"
	elif option == 2:
		print "INSIDE shapeChange"
		SHAPE = "circle"
	elif option == 3:
		SHAPE = "quad"
	else:
		print "INSIDE shapeChange else"
		SHAPE = "line"
	DrawSystem()
	return 0
	
def colorChange(option):
	global colorR, colorB, colorG
	if option == 4:
		colorR=1.0
		colorB=0.0
		colorG=0.0
		print "Colorchange"
		DrawSystem()
	elif option == 5:
		colorR=0.9
		colorB=0.6
		colorG=0.5
		print "Colorchange"
		DrawSystem()
	return 0

def processMenuEvents(option):
    global SIZE,AXIOM,RULES,ANGLE,ITERATE,TREE,XS
    if option == 1:
        TREE = False
        L_System( 0.01,'FX',{'X':'X+FY','Y':'FX-Y'},90).draw(10)
        SIZE  = 0.01
        XS = SIZE
        AXIOM = 'FX'
        RULES = {'X':'X+FY','Y':'FX-Y'}
        ANGLE = 90
        ITERATE = 10
    elif option == 2:
        TREE = False
        L_System(0.01,'F++F++F',{'F':'F-F++F-F'},60).draw(3)
        SIZE = 0.01
        XS = SIZE
        AXIOM = 'F++F++F'
        RULES = {'F':'F-F++F-F'}
        ANGLE = 60
        ITERATE = 3
    elif option == 3:
        TREE = False
        L_System(0.01,'FA', {'FA': 'FB-FA-FB', 'FB': 'FA+FB+FA'}, 60).draw(4)
        SIZE = 0.01
        XS = SIZE
        AXIOM = 'FA'
        RULES = {'FA': 'FB-FA-FB', 'FB': 'FA+FB+FA'}
        ANGLE = 60
        ITERATE = 8
    elif option==4:
        TREE = True
        L_System(0.007,'FX', {'X': 'F-[[X]+X]^F[+FX]-X', 'F': 'FF'}, 25).draw(6)

        SIZE = 0.007
        XS = SIZE
        AXIOM = 'FX'
        RULES = {'X': 'F-[[X]+X]^F[+FX]-X', 'F': 'FF'}
        ANGLE = 25
        ITERATE = 6
    else:
        file_handle()
    return 0

def keyboard(key,x,y):
    global TD,SIZE,XS
    if key == chr(27):
        sys.exit(0)
    if key == 'r': 
        TD = (TD + 15)%360
    if key == 'R':
        TD = (TD - 15)%360   
        TD = -(360-TD)
        print TD
    if key == 'z':
        SIZE = SIZE + (SIZE*0.05)
    if key == 'Z':
        SIZE = SIZE - (SIZE*0.05)
    if key == 's':
        XS = XS  + (0.05)
    if key == 'S':
        XS = XS - (0.05)

    DrawSystem()

def initialize():
    global world_coord
    glColor3d(1.0,0.0,0.0)
    glClearDepth(1.0)
    glDepthFunc(GL_LESS)
    glEnable(GL_DEPTH_TEST)
    glDepthMask(GL_TRUE)
    glClear (GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT)
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    #glFrustum(-1.0,1.0,-1.0,1.0,1.5,20.0)
    #gluPerspective(40.0,(width)/height,0.01,20.0)
    gluOrtho2D(world_coord.l,world_coord.r,world_coord.b,world_coord.t)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()
    #gluLookAt(0.0,0.0,8.0,0.0,0.0,0.0,0.0,1.0,0.0)

if __name__=='__main__':
	glutInit(sys.argv)
	glutInitDisplayMode(GLUT_DEPTH | GLUT_RGB)
	glutInitWindowSize(width, height)
	glutInitWindowPosition(100, 100)
	glutCreateWindow("L-Systems Generator")
	glutReshapeFunc(onResize)
	initialize()
	createMenu()
	glutDisplayFunc(display)
	glutKeyboardFunc(keyboard)
	file_handle()
	glutMainLoop()

